"""initial deployment

Revision ID: fbb13f56cc9f
Revises: 
Create Date: 2024-04-01 23:02:10.100954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb13f56cc9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('dated', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dated'), ['dated'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('directories',
    sa.Column('directories_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=4), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=4000), nullable=False),
    sa.Column('dated', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('directories_id')
    )
    with op.batch_alter_table('directories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directories_dated'), ['dated'], unique=False)
        batch_op.create_index(batch_op.f('ix_directories_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directories_user_id'))
        batch_op.drop_index(batch_op.f('ix_directories_dated'))

    op.drop_table('directories')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_dated'))

    op.drop_table('user')
    # ### end Alembic commands ###
